---
title: "Test"
author: "Mariola Espinosa"
date: "2/18/2019"
output: pdf_document
csl: /Users/mespinos/Library/texmf/bibtex/csl/chicago-fullnote-bibliography-with-ibid.csl
bibliography: /Users/mespinos/Library/texmf/bibtex/bib/MELibrary.bib
---

# Citations and Footnotes
- Use `[@citekey]` to cite to a source; citekey will be in AuthorYear format.[@Espinosa2009]  
- To cite additional works, separate them with a semicolon.[@Espinosa2009; @Humphreys1992]  The citations will appear in their own footnote in the order you listed them.
- To add a page number, just put it after a comma[@Espinosa2009, 33-35].
- To add an introductory comment, like "see," use a second, leading set of square brackets[See @Espinosa2009, at 33-35].
- Drop a textual footnote like this.^[This is a footnote.]
- To cite within a textual footnote.^[Do it like usual; see @Espinosa2009.]	
- To get a source into the bibliography without actually citing it, define a dummy nocite metadata field in the header at the top and put the citations up there:

```
nocite: |
    @item1, @item2
```


# Other Stuff

To create a section heading: `# Yellow Fever`. 
To create a subsection heading: `## Yellow Fever`. 
To emphasize a word with italics: This word is _important_.
Block quotes start with >

>During Cuba's Ten Years War of 1868 to 1878, the heat and rains of the summer months brough the threat of yellow fever to the battlefront.  The "invincible Generals June, July, and August" in this way served as allies for the Cuban Liberation Army in the conflict.[@Espinosa2009 1]

Of course, it was all yellow fever, all the time.



\pagebreak

# Bibliography

